theme = "gruvbox"

[editor]
auto-pairs = false
indent-heuristic = "tree-sitter"
indent-guides.render = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
"A-u" = "switch_to_lowercase"
"A-U" = "switch_to_uppercase"

[keys.normal."\\"]
r = ":reflow"

# "\b" is "reformat" via black
b = ["select_all", ":pipe black -q -", "goto_last_modification"]

# "\f" is "reformat" via pre-commit
f = [
  ":w",
  # using `:sh` to execute seems to block, and the reload fails to run
  # nesting in an echo "forces" it
  ":echo %sh{pre-commit run --files %{buffer_name} > /dev/null || true}",
  ":reload",
]

[keys.select]
"A-u" = "switch_to_lowercase"
"A-U" = "switch_to_uppercase"

"A-g" = ":pipe github-coauthor -"
[keys.select."\\"]
r = ":reflow"
